[package]
name = "scribble-workspace"
version = "0.1.0"
edition = "2021"
authors = ["Caleb J.D. Terkovics <isdood>"]
description = "A kernel & OS written in rust - Workspace Root"
repository = "https://github.com/isdood/scribble"
license = "MIT"

[workspace]
members = [
    "lib/unstable_matter",
    "lib/shard",
    "lib/wanda",
    "lib/scribble"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Caleb J.D. Terkovics <isdood>"]
edition = "2021"

[workspace.dependencies]
libm = "0.2.11"

[lib]
path = "src/lib.rs"

[dependencies]
libm = "0.2.11"
scribble = { path = "lib/scribble" }
