[workspace]
members = [
    "boot/spINIT",
    "boot/spinUP",
    "boot/spun",
    "lib/scribble",
    "lib/unstable_matter"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["isdood"]

[workspace.metadata]
last_updated = "2025-01-12T23:03:15Z"
maintained_by = "isdood"


