[package]
name = "scribble"
version = "0.0.1"
authors = ["Caleb J.D. Terkovics <calebjdt@gmail.com>"]
edition = "2018"

[dependencies]
spin = "0.9.2"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
x86_64 = "0.14.9"
pic8259 = "0.10.2"
uart_16550 = "0.2.14"
pc-keyboard = "0.5.0"
linked_list_allocator = "0.9.0"
volatile = "0.4.3"
llvm = "0.0.1"

[dev-dependencies]
bootimage = "0.10.2"

[build-dependencies]
# No need to reference the bootloader here

[package.metadata.bootloader]
target = "bootloader/x86_64-scribble.json"  # Ensure this matches the new target file

[features]
alloc = []
