[package]
name = "scribble"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2018"

[dependencies]
bootloader = "0.10.6"
spin = "0.9.2"
lazy_static = "1.4.0"
x86_64 = "0.14.9"
pic8259 = "0.10.2"
uart_16550 = "0.2.14"
pc_keyboard = "0.5.0"

[features]
# Enable the `alloc` feature of the standard library
alloc = []

[dev-dependencies]
bootimage = "0.10.2"

[build-dependencies]
bootloader = "0.10.6"
