[package]
name = "scribble"
version = "0.1.0"
authors = ["Caleb J.D. Terkovics"]
edition = "2018"

[dependencies]
x86_64 = "0.14.13"
bootloader = "0.9.29"
volatile = "0.4.6"
spin = "0.9.8"
lazy_static = "1.5.0"
linked_list_allocator = "0.9.1"
uart_16550 = "0.2.19"
pc-keyboard = "0.5.1"
pic8259 = "0.10.4"

[build-dependencies]
bootimage = "0.10.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
