[package]
name = "scribble"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = { version = "0.9.23", features = ["map_physical_memory"] }
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = { version = "0.14.2", features = ["instructions"] }
pic8259 = "0.10.1"
pc-keyboard = "0.5.0"
linked_list_allocator = "0.10.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
lazy = "0.5.3"
static = "0.0.4"
bootimage = "0.10.3"

[package.metadata.bootimage]
run-command = ["qemu-system-x86_64", "-drive", "format=raw,file={}"]
run-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
    "-display", "none",
    "-serial", "stdio"
]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
    "-display", "none",
    "-serial", "stdio"
]
test-success-exit-code = 33

[[bin]]
name = "scribble"
test = false
bench = false
