[package]
name = "scribble-workspace"
version = "0.1.0"
edition = "2021"
authors = ["Caleb J.D. Terkovics <isdood>"]
description = "A kernel & OS written in rust - Workspace Root"
repository = "https://github.com/isdood/scribble"
license = "MIT"

[workspace]
members = [
    "lib/unstable_matter",
    "lib/shard",
    "lib/wanda",
    "lib/scribble",
    "lib/carve",
    "lib/magicmath",
    "lib/harmony_core",
    "lib/garnet",
    "lib/quartz",
    "lib/scribe",
    "lib/errors",
    "lib/error_derive",
    "lib/error_core",
    "lib/ziggy"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Caleb J.D. Terkovics <isdood>"]
edition = "2021"

[workspace.dependencies]
libm = "0.2.11"
harmony_core = { path = "lib/harmony_core" }
shard = { path = "lib/shard" }
quartz = { path = "lib/quartz" }
scribe = { path = "lib/scribe" }
errors = { path = "lib/errors" }
error_derive = { path = "lib/error_derive" }
error_core = { path = "lib/error_core" }
ziggy = { path = "lib/ziggy" }
criterion = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "bench_compare"
path = "tools/bench_compare.rs"

[dependencies]
libm = "0.2.11"
scribble = { path = "lib/scribble" }
scribe = { path = "lib/scribe" }
errors = { path = "lib/errors" }
error_derive = { path = "lib/error_derive" }
error_core = { path = "lib/error_core" }
ziggy = { path = "lib/ziggy" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
criterion = "0.5"

# Metadata
[package.metadata]
created = "2025-01-19"
updated = "2025-01-20 20:09:12"
current_user = "isdood"
