[workspace]
resolver = "2"
members = [
    "boot/spinUP",
    "boot/spINIT",
    "boot/spun",
    "lib/unstable_matter",
    "lib/scribble"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
