[package]
name = "scribble"
version = "0.1.0"
authors = ["Caleb J.D. Terkovics"]
edition = "2018"

[dependencies]
x86_64 = { version = "0.14.13", default-features = false }
bootloader = { version = "0.9.29", default-features = false }
volatile = { version = "0.4.6", default-features = false }
spin = { version = "0.9.8", default-features = false }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
linked_list_allocator = { version = "0.9.1", default-features = false }
uart_16550 = { version = "0.2.19", default-features = false }
pc_keyboard = { version = "0.5.1", default-features = false }
pic8259 = { version = "0.10.4", default-features = false }

[build-dependencies]
bootimage = "0.10.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "x86_64-scribble.json"
