[workspace]
members = [
    "boot/spINIT",    # Note the capital 'I'
    "boot/spinUP",    # Note the capital 'UP'
    "boot/spun",
    "lib/unstable_matter"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["isdood"]

[workspace.metadata]
last_updated = "2025-01-12T22:30:44Z"
maintained_by = "isdood"

