[package]
name = "scribble"
version = "0.1.0"
authors = ["Caleb J.D. Terkovics"]
edition = "2018"

[dependencies]

[build-dependencies]
bootimage = "0.10.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
