[package]
name = "scribble"
version = "0.0.1"
edition = "2021"

[dependencies]
x86_64 = "0.14.2"
spin = "0.9.8"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
uart_16550 = "0.2.19"
pic8259 = "0.10.4"
pc-keyboard = "0.7.0"
linked_list_allocator = "0.10.5"
unstable_matter = { path = "lib/unstable_matter" }
spinUP = { path = "./spinUP/gear2", lib = true }

[workspace]
members = [
    "lib/unstable_matter",
    "spinUP/gear2"
]
