[package]
name = "scribble"
version = "0.1.0"
authors = ["Caleb J.D. Terkovics <your.email@example.com>"]
edition = "2018"

[dependencies]
bootloader = "0.10.6"
spin = "0.9.2"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
x86_64 = "0.14.9"
pic8259 = "0.10.2"
uart_16550 = "0.2.14"
pc-keyboard = "0.5.0"
linked_list_allocator = "0.9.0"
volatile = "0.4.3"

[dev-dependencies]
bootimage = "0.10.2"

[build-dependencies]
bootloader = "0.10.6"

[features]
alloc = []
