[package]
name = "scribble"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.29"
volatile = "0.4.6"
spin = "0.9.8"
x86_64 = "0.14.13"
uart_16550 = "0.2.19"
pic8259 = "0.10.4"
pc-keyboard = "0.5.1"
linked_list_allocator = "0.9.1"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
