[build]
target = "i686-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.i686-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "target-feature=+soft-float",
    "-C", "opt-level=z",
    "-C", "no-redzone=yes",
    "-C", "code-model=tiny",
    "-C", "relocation-model=static",
    "-Z", "merge-functions=yes",
    "-C", "panic=abort",
    "-C", "strip=symbols",
]

[target.'cfg(target_os = "none")']
runner = "echo"
