[build]
rustflags = [
    "-C", "link-args=-nostartfiles -Wl,--gc-sections -Wl,-T../linker.ld",
    "-C", "link-args=--no-eh-frame-hdr",
    "-C", "link-args=--build-id=none",
    "-C", "relocation-model=static",
    "-C", "opt-level=z"
]

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]
