[build]
target = "i686-spinup"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[target.i686-spinup]
rustflags = [
    "-C", "opt-level=z",
    "-C", "no-redzone",
    "-C", "link-args=-Tlinker.ld",
    "-C", "link-args=--oformat=binary",
    "-C", "link-args=-static",
    "-C", "link-args=--nmagic"
]
linker = "ld.lld"
