[build]
rustflags = [
    "-C", "link-args=-nostartfiles -static",
    "-C", "link-args=--no-eh-frame-hdr",
    "-C", "link-args=--build-id=none",
    "-C", "target-feature=-mmx,-sse,+soft-float",
    "-C", "relocation-model=static"
]

[target.i686-unknown-linux-gnu]
linker = "ld.lld"
