[build]
target = "x86_64-spinUP"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[target.x86_64-spinUP]
runner = "qemu-system-x86_64 -drive format=raw,file={}"
