[build]
target = "i686-spinup"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[target.i686-spinup]
rustflags = [
    "-C", "opt-level=s",
    "-C", "no-redzone",
    "-C", "relocation-model=static",
    "-C", "code-model=small",
    "-C", "link-arg=-N",
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=--oformat=binary",
    "-C", "link-arg=-nostartfiles"
]
