[build]
target = "i686-spinup"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[target.i686-spinup]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=--oformat=binary",
    "-C", "link-arg=--strip-all",
    "-C", "link-arg=-N"
]
linker = "ld.lld"
