[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "i686-scribble.json"

[target.'cfg(target_os = "none")']
runner = "qemu-system-i386 -fda disk.img"
