[build]
target = "i686-spinup"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[target.i686-spinup]
rustflags = [
    "-C", "opt-level=z",
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=--oformat=binary"
]
linker = "ld.lld"
