[build]
target = "i686-spinup"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[target.i686-spinup]
rustflags = [
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-static",
    "-C", "link-arg=-Tlinker.ld",
    "-C", "code-model=small"
]
