[build]
target = "x86_64-spinUP"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-spinUP]
runner = "bootimage runner"
rustflags = [
    "-C", "code-model=kernel",
    "-C", "relocation-model=static"
]
