[package]
name = "spinUP"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "spinUP-gear2"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
x86_64 = "0.14"  # Add this line
unstable_matter = { path = "../../lib/unstable_matter" }
