[package]
name = "spinUP"
version = "0.1.0"
edition = "2021"

[dependencies]
unstable_matter = { path = "../../lib/unstable_matter" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
