[package]
name = "spinUP"
version = "0.1.0"
edition = "2021"
authors = ["Caleb J.D. Terkovics <calebjdt@gmail.com>"]

[dependencies]
uart_16550 = "0.2"
spin = "0.9.2"
x86_64 = "0.14"
unstable_matter = { path = "../../lib/unstable_matter" }

[features]
default = []

[package.metadata]
cargo-features = ["asm"]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 'z'  # Optimize for size
lto = true       # Enable Link Time Optimization
codegen-units = 1 # Optimize for size
panic = "abort"  # Remove panic unwinding code
strip = true     # Remove debug symbols
