[package]
name = "spinUP"
version = "0.1.0"
edition = "2021"
authors = ["isdood"]

[dependencies]
x86_64 = "0.14.2"
volatile = "0.2.6"
spin = "0.5.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
