# boot/spINIT/Cargo.toml
[package]
name = "spinit"  # Lowercase package name
version = "0.1.0"
edition = "2021"
authors = ["isdood"]

[dependencies]
unstable_matter = { path = "../../lib/unstable_matter" }
scribble = { path = "../../lib/scribble" }
